version: '3.4'

services:
  apiwipace:
    image: apiwipace
    build:
      context: API-TFG
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      JWT_SECRET: 97ddbc2c8401b4006ceeff76b6fbb6be4405a0a8406cbf1c6354f21bd2771abd48b6848f9d8b1d9360c41851d32a8925e1fece173ba238cb7cd8630014d00724
      JWT_EXPIRES_IN: 1h
      DB_URL: mongodb://wipacedb:27017/tfg
    ports:
      - 8081:8081
    depends_on:
      - wipacedb
    networks:
      - app-network

  frontwipace:
    image: frontwipace
    build:
      context: FRONT-TFG
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
    networks:
      - app-network

  wipacedb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    ports:
      - 27017:27017

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
