apiVersion: apps/v1
kind: Deployment
metadata:
  name: waf 
spec:
  replicas: 1
  selector:
    matchLabels:
      name: waf 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: waf 
    spec:
      containers:
      - name: modsecurity-proxy
        image: jrbalsas/modsecurity:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT #WAF port
          value: "80"
          # Webservice URL
        - name: BACKEND
          value: "http://wipace-service:8081"
        - name: RULE_ENGINE
          value: "On"  #On/Off/DetectionOnly
        - name: PARANOIA
          value: "1"
        # Detailed adjustment 
        - name: ANOMALY_INBOUND
          value: "5"
        - name: ANOMALY_OUTBOUND
          value: "4"
        # Disable detailed logs
        # - name: APACHE_ACCESSLOG
        #   value: "/dev/null"
        # - name: MODSEC_AUDIT_LOG
        #   value: "/dev/null"
        ports:
          - containerPort: 80
          # Limit resources for GKE g1-small instance
        resources:
          limits:
            cpu: 50m
          requests:
            cpu: 20m
        #GKE ingress uses readinessProbe for health checking
        #readinessProbe:
        #  httpGet:
        #    path: /healthz
        #    port: 80
        #  periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: waf 
spec:
  selector:
    name: waf 
  ports:
    - port: 80
      nodePort: 30081
      protocol: TCP
  type: NodePort
